/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 微信小程序登录
         * @description code2session 换 openid/unionid，返回访问令牌。首次登录返回是否需弹协议。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description wx.login 获取的临时凭证 */
                        code: string;
                        /** @description 手机号快速验证组件 code，未授权手机号时不传 */
                        phoneCode?: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["LoginVO"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/agreements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取协议富文本 */
        get: {
            parameters: {
                query: {
                    type: "SERVICE" | "PRIVACY" | "RECHARGE" | "INSURANCE";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: {
                                title?: string;
                                /** @description 富文本 HTML */
                                content?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前站点与小区信息
         * @description 对应 PRD P1 顶部站点栏「泷景花园 · 泷景中央站」
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["SiteVO"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 已开通小区列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["CommunityVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community-applies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 申请开通我的小区 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        communityName: string;
                        contactPhone?: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/banners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 首页 Banner 与公告 */
        get: {
            parameters: {
                query?: {
                    siteId?: components["parameters"]["SiteId"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["BannerVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capacity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 今晚剩余产能
         * @description 对应 PRD P1 产能条「今晚剩余 8 个名额 · 最晚 23:00 存钥匙」
         */
        get: {
            parameters: {
                query?: {
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["CapacityVO"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 服务分类（洗车服务 / 美容服务） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["ServiceCategoryVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 服务项列表 */
        get: {
            parameters: {
                query?: {
                    categoryId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["ServiceVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 服务项详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serviceId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["ServiceDetailVO"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cabinets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 机柜列表（含空闲格口数与距离） */
        get: {
            parameters: {
                query?: {
                    communityId?: components["parameters"]["CommunityId"];
                    /** @description 楼栋/单元模糊搜索 */
                    keyword?: string;
                    lng?: number;
                    lat?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["CabinetVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的车辆列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["VehicleVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 新增车辆 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VehicleRequest"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vehicleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改车辆 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VehicleRequest"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        post?: never;
        /** 删除车辆（前端需二次确认） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的订单列表（三 Tab） */
        get: {
            parameters: {
                query?: {
                    tab?: "ONGOING" | "WAIT_REVIEW" | "ALL";
                    pageNum?: components["parameters"]["PageNum"];
                    pageSize?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: {
                                list?: components["schemas"]["OrderListItemVO"][];
                                /** Format: int64 */
                                total?: number;
                                pageNum?: number;
                                pageSize?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 提交订单
         * @description 后端按顺序校验：格口可用 → 产能未超 → 车辆/地址/机柜/协议齐全。
         *     成功后生成 WAIT_PAY 订单并预占格口（TTL 15 分钟，与支付倒计时一致）。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 幂等键，客户端生成 UUID，同一键重复提交返回首次结果 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrderRequest"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["CreateOrderVO"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderNo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 订单详情（含 8 节点时间轴与证据） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["OrderDetailVO"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderNo}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取消订单
         * @description 走状态机 CANCEL 事件。客户自助仅限 WAIT_PAY / WAIT_KEY / KEY_IN / PICKING，
         *     其余状态返回 B1002。取消后释放格口、回补产能、返还权益并自动触发退款。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderNo}/open-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取开箱码（存/取钥匙） */
        get: {
            parameters: {
                query: {
                    action: "DEPOSIT" | "TAKE_BACK" | "EMERGENCY";
                };
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["OpenCodeVO"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderNo}/emergency-take-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 紧急取钥匙
         * @description 未取车 → 立即告警 + 取消 + 全额退款；
         *     已在清洗 → 返回预计完成时间并拒绝取回（错误码 B1002）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{orderNo}/prepay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 获取微信支付参数 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: {
                                timeStamp?: string;
                                nonceStr?: string;
                                package?: string;
                                signType?: string;
                                paySign?: string;
                                /**
                                 * Format: int64
                                 * @description 支付截止时间（毫秒时间戳），前端倒计时以此为准
                                 */
                                expireAt?: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{orderNo}/mock-pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 模拟支付成功（仅本地开发）
         * @description 开发期替代微信支付回调，触发状态机 PAY_SUCCESS 事件（WAIT_PAY → WAIT_KEY）。
         *     由配置项 wash.pay.mock-enabled 控制，生产环境必须为 false，否则返回 A0003。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["PayResultVO"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderNo}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 提交评价
         * @description 走状态机 REVIEW_SUBMIT 事件（WAIT_REVIEW → FINISHED）。≤4 星强制填原因并生成复盘工单。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        rating: number;
                        /** @description 洗得干净 / 时效快 / 服务态度好 / 取送准时 */
                        tags?: string[];
                        content?: string;
                        /** @description 已上传图片的 fileId */
                        images?: string[];
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/after-sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交售后（重洗 / 退款 / 理赔） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        orderNo: string;
                        /** @enum {string} */
                        type: "REWASH" | "REFUND" | "CLAIM";
                        reason?: string;
                        images?: string[];
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: {
                                ticketNo?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/faqs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 常见问题标签与解答 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["FaqVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/customer-service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 客服配置（企微二维码、双电话、夜间提示） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: {
                                wecomQrcodeUrl?: string;
                                platformPhone?: string;
                                stationPhone?: string;
                                nightTip?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Result: {
            /**
             * @description 0 = 成功，非 0 见 x-error-codes。
             *     数字映射规则：分段字母转前缀（A=1 / B=2 / C=3）+ 4 位编号，
             *     即 A0002 → 10002、B1002 → 21002、C0001 → 30001。
             * @example 0
             */
            code: number;
            /** @example 操作成功 */
            msg: string;
            /** @description 业务数据，各接口不同 */
            data?: unknown;
            /** @description 链路追踪 ID，排查问题时提供 */
            traceId?: string;
        };
        /**
         * @description 订单状态，取值必须与《订单状态机规则表.md》及 OrderStatus 枚举完全一致（15 个）。
         * @enum {string}
         */
        OrderStatus: "WAIT_PAY" | "WAIT_KEY" | "KEY_IN" | "PICKING" | "TO_STATION" | "WASHING" | "QC" | "WAIT_RETURN" | "RETURNING" | "RETURNED" | "WAIT_REVIEW" | "FINISHED" | "CANCELED" | "REFUNDING" | "REFUNDED";
        TimelineNode: {
            /**
             * @description 已下单 / 钥匙已入柜 / 已取车 / 到达中央站 / 清洗中 / 质检完成 / 已还车 / 待取钥匙
             * @enum {string}
             */
            node?: "ORDERED" | "KEY_IN" | "PICKED" | "ARRIVED" | "WASHING" | "QC_DONE" | "RETURNED" | "WAIT_TAKE_KEY";
            title?: string;
            /**
             * Format: int64
             * @description 毫秒时间戳，未到达时为空
             */
            time?: number;
            reached?: boolean;
            current?: boolean;
            /** @description 该节点的照片等证据 */
            evidences?: components["schemas"]["MediaVO"][];
        };
        LoginVO: {
            token?: string;
            /** Format: int64 */
            expireAt?: number;
            isNewUser?: boolean;
            /** @description true 时前端弹《用户服务协议》《隐私政策》 */
            needAgreement?: boolean;
            phoneBound?: boolean;
        };
        SiteVO: {
            /** Format: int64 */
            siteId?: number;
            siteName?: string;
            /** Format: int64 */
            communityId?: number;
            communityName?: string;
            /** @description 站点栏展示文案，如「泷景花园 · 泷景中央站」 */
            displayName?: string;
            /**
             * @description 正常 / 停业 / 雨天模式
             * @enum {string}
             */
            serviceStatus?: "OPEN" | "CLOSED" | "RAINY";
            closedNotice?: string;
        };
        CommunityVO: {
            /** Format: int64 */
            communityId?: number;
            name?: string;
            /** @description 地库通行授权，false 时禁止该小区下单 */
            accessAuth?: boolean;
            enabled?: boolean;
        };
        BannerVO: {
            /** Format: int64 */
            bannerId?: number;
            imageUrl?: string;
            title?: string;
            /** @enum {string} */
            linkType?: "NONE" | "ACTIVITY" | "RECHARGE" | "SERVICE";
            linkValue?: string;
            sort?: number;
        };
        CapacityVO: {
            /** Format: date */
            date?: string;
            total?: number;
            used?: number;
            remaining?: number;
            /** @description 最晚存钥匙时间，如 23:00 */
            depositDeadline?: string;
            /** @description 承诺还车时间，如 次日 07:00 */
            promiseReturnTime?: string;
            soldOut?: boolean;
        };
        ServiceCategoryVO: {
            /** Format: int64 */
            categoryId?: number;
            /** @example 洗车服务 */
            name?: string;
            sort?: number;
        };
        ServiceVO: {
            /** Format: int64 */
            serviceId?: number;
            /** Format: int64 */
            categoryId?: number;
            name?: string;
            subtitle?: string;
            /** @description 原价，单位分 */
            originPrice?: number;
            /** @description 活动价，单位分 */
            salePrice?: number;
            /** @description 会员价，单位分；非会员为空 */
            memberPrice?: number;
            /** @description 实际展示价，优先级 会员价 > 活动价 > 原价，由后端算好 */
            displayPrice?: number;
            workMinutes?: number;
            /** @description 取送车费，固定展示 0（卖点） */
            pickupFee?: number;
            dailyLimit?: number;
            /** @description 今日已约满 */
            soldOut?: boolean;
            coverUrl?: string;
        };
        ServiceDetailVO: components["schemas"]["ServiceVO"] & {
            /** @description 服务内容清单 */
            items?: string[];
            applicableModels?: string;
            notIncluded?: string[];
            notices?: string[];
            sampleImages?: string[];
        };
        CabinetVO: {
            /** Format: int64 */
            cabinetId?: number;
            /** @description 命名规范 小区名+楼栋+单元+楼层，如「泷景花园 三号楼二单元负一」 */
            name?: string;
            slotTotal?: number;
            slotFree?: number;
            online?: boolean;
            /** @description 距您约多少米；未授权定位时为空 */
            distance?: number;
            full?: boolean;
        };
        VehicleVO: {
            /** Format: int64 */
            vehicleId?: number;
            plateNo?: string;
            brand?: string;
            color?: string;
            photoUrl?: string;
            isNewEnergy?: boolean;
            isDefault?: boolean;
            address?: components["schemas"]["AddressVO"];
        };
        AddressVO: {
            /** Format: int64 */
            communityId?: number;
            building?: string;
            unit?: string;
            /** @example 负一层 */
            floor?: string;
            /** @example A 区 23 号车位 */
            parkingNo?: string;
        };
        VehicleRequest: {
            /** @description 支持新能源 8 位 */
            plateNo: string;
            brand?: string;
            color?: string;
            photoFileId?: string;
            isNewEnergy?: boolean;
            isDefault?: boolean;
            address?: components["schemas"]["AddressVO"];
        };
        CreateOrderRequest: {
            /** Format: int64 */
            serviceId: number;
            /** Format: int64 */
            vehicleId: number;
            /** Format: int64 */
            cabinetId: number;
            /** Format: date */
            appointDate: string;
            /** @example 19:00 */
            appointTime: string;
            /**
             * @description 是否需要取送车，V1.0 固定 true
             * @default true
             */
            pickupRequired: boolean;
            remark?: string;
            parkPhotoFileIds?: string[];
            /** @description 已同意《服务条款与钥匙寄存协议》 */
            agreed: boolean;
        };
        CreateOrderVO: {
            /** @example SE202609151601276839838676768265 */
            orderNo?: string;
            status?: components["schemas"]["OrderStatus"];
            /** @description 应付金额，单位分 */
            payAmount?: number;
            /**
             * Format: int64
             * @description 支付截止时间，毫秒时间戳
             */
            payExpireAt?: number;
        };
        OrderListItemVO: {
            orderNo?: string;
            status?: components["schemas"]["OrderStatus"];
            statusLabel?: string;
            serviceName?: string;
            workMinutes?: number;
            /** Format: int64 */
            appointTime?: number;
            communityName?: string;
            plateNo?: string;
            payAmount?: number;
            mainAction?: components["schemas"]["OrderAction"];
            subActions?: components["schemas"]["OrderAction"][];
        };
        OrderDetailVO: {
            orderNo?: string;
            status?: components["schemas"]["OrderStatus"];
            statusLabel?: string;
            /** @example 清洗中 · 预计次日 6:30 送回原位 */
            statusDesc?: string;
            /** Format: int64 */
            promiseReturnTime?: number;
            overdue?: boolean;
            siteName?: string;
            cabinetName?: string;
            /** @description 仅本人可见 */
            slotNo?: string;
            plateNo?: string;
            address?: components["schemas"]["AddressVO"];
            serviceName?: string;
            remark?: string;
            originAmount?: number;
            discountAmount?: number;
            payAmount?: number;
            payType?: string;
            timeline?: components["schemas"]["TimelineNode"][];
            medias?: components["schemas"]["MediaVO"][];
            mainAction?: components["schemas"]["OrderAction"];
            subActions?: components["schemas"]["OrderAction"][];
        };
        /** @description 模拟支付返回（x-dev-only） */
        PayResultVO: {
            orderNo?: string;
            status?: components["schemas"]["OrderStatus"];
        };
        /** @description 按钮随状态机变化，前端不得自行推断，一律用后端返回值 */
        OrderAction: {
            /** @enum {string} */
            action?: "PAY" | "DEPOSIT_KEY" | "VIEW_PROGRESS" | "TAKE_KEY" | "REVIEW" | "REORDER" | "CANCEL" | "CONTACT_SERVICE";
            label?: string;
            enabled?: boolean;
        };
        OpenCodeVO: {
            /** @description 6 位取件码 */
            code?: string;
            qrcodeUrl?: string;
            cabinetName?: string;
            slotNo?: string;
            /** Format: int64 */
            expireAt?: number;
        };
        MediaVO: {
            fileId?: string;
            /** @enum {string} */
            bizType?: "PARK" | "PICK" | "WASHED" | "RETURN" | "COMPARE" | "VIDEO";
            /** @description 临时访问地址，带有效期 */
            url?: string;
            /** Format: int64 */
            uploadTime?: number;
        };
        FaqVO: {
            /** Format: int64 */
            faqId?: number;
            /** @example 无法打开柜门 */
            label?: string;
            answer?: string;
            /** @description 绑定的工单类型，一键建单时带入 */
            ticketType?: string;
        };
    };
    responses: never;
    parameters: {
        PageNum: number;
        PageSize: number;
        SiteId: number;
        CommunityId: number;
        /** @description 幂等键，客户端生成 UUID，同一键重复提交返回首次结果 */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
