/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 微信小程序登录
         * @description code2session 换 openid/unionid，返回访问令牌。首次登录返回是否需弹协议。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description wx.login 获取的临时凭证 */
                        code: string;
                        /** @description 手机号快速验证组件 code，未授权手机号时不传 */
                        phoneCode?: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["LoginVO"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/worker/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 师傅工号登录
         * @description 师傅端入口。工号 + 密码登录（MVP 先密码，后续可换短信码）。
         *     返回带 role=WORKER 的访问令牌，与 C 端微信登录令牌隔离。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 工号 */
                        workerNo: string;
                        /** @description 登录密码 */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["WorkerLoginVO"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/agreements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取协议富文本 */
        get: {
            parameters: {
                query: {
                    type: "SERVICE" | "PRIVACY" | "RECHARGE" | "INSURANCE";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: {
                                title?: string;
                                /** @description 富文本 HTML */
                                content?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前站点与小区信息
         * @description 对应 PRD P1 顶部站点栏「泷景花园 · 泷景中央站」
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["SiteVO"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 已开通小区列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["CommunityVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community-applies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 申请开通我的小区 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        communityName: string;
                        contactPhone?: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/banners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 首页 Banner 与公告 */
        get: {
            parameters: {
                query?: {
                    siteId?: components["parameters"]["SiteId"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["BannerVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capacity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 今晚剩余产能
         * @description 对应 PRD P1 产能条「今晚剩余 8 个名额 · 最晚 23:00 存钥匙」
         */
        get: {
            parameters: {
                query?: {
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["CapacityVO"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 服务分类（洗车服务 / 美容服务） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["ServiceCategoryVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 服务项列表 */
        get: {
            parameters: {
                query?: {
                    categoryId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["ServiceVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 服务项详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serviceId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["ServiceDetailVO"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cabinets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 机柜列表（含空闲格口数与距离） */
        get: {
            parameters: {
                query?: {
                    communityId?: components["parameters"]["CommunityId"];
                    /** @description 楼栋/单元模糊搜索 */
                    keyword?: string;
                    lng?: number;
                    lat?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["CabinetVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的车辆列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["VehicleVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 新增车辆 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VehicleRequest"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vehicleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改车辆 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VehicleRequest"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        post?: never;
        /** 删除车辆（前端需二次确认） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的订单列表（三 Tab） */
        get: {
            parameters: {
                query?: {
                    tab?: "ONGOING" | "WAIT_REVIEW" | "ALL";
                    pageNum?: components["parameters"]["PageNum"];
                    pageSize?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: {
                                list?: components["schemas"]["OrderListItemVO"][];
                                /** Format: int64 */
                                total?: number;
                                pageNum?: number;
                                pageSize?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 提交订单
         * @description 后端按顺序校验：格口可用 → 产能未超 → 车辆/地址/机柜/协议齐全。
         *     成功后生成 WAIT_PAY 订单并预占格口（TTL 15 分钟，与支付倒计时一致）。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 幂等键，客户端生成 UUID，同一键重复提交返回首次结果 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrderRequest"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["CreateOrderVO"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderNo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 订单详情（含 8 节点时间轴与证据） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["OrderDetailVO"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderNo}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取消订单
         * @description 走状态机 CANCEL 事件。客户自助仅限 WAIT_PAY / WAIT_KEY / KEY_IN / PICKING，
         *     其余状态返回 B1002。取消后释放格口、回补产能、返还权益并自动触发退款。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderNo}/open-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 获取开箱码（存/取钥匙）
         * @description 仅「待存钥匙 WAIT_KEY」与「已送回 RETURNED」两个环节可调用，后端按订单状态自行判定存/取，
         *     前端无需传 action。开箱码 10 分钟内有效，仅可使用一次（取码即写入开箱留痕，明文不留库）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["OpenCodeVO"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderNo}/emergency-take-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 紧急取钥匙
         * @description 未取车 → 立即告警 + 取消 + 全额退款；
         *     已在清洗 → 返回预计完成时间并拒绝取回（错误码 B1002）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{orderNo}/prepay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 获取微信支付参数 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: {
                                timeStamp?: string;
                                nonceStr?: string;
                                package?: string;
                                signType?: string;
                                paySign?: string;
                                /**
                                 * Format: int64
                                 * @description 支付截止时间（毫秒时间戳），前端倒计时以此为准
                                 */
                                expireAt?: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device-callback/v1/slot/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 柜机回调：钥匙已存入
         * @description 客户凭开箱码打开格口并放入钥匙后，柜机回调本接口，触发状态机 DEPOSIT_KEY（WAIT_KEY → KEY_IN）。
         *     生产环境必须校验柜机签名 + IP 白名单（当前实现仅校验开箱码，接入硬件时补签名校验）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        orderNo: string;
                        /** @description 6 位开箱码 */
                        code: string;
                        slotNo?: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/wechat/notify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 微信支付结果回调
         * @description 由微信支付服务器调用，无需登录态。必须：① 验签 ② 幂等（同一通知多次到达只处理一次）
         *     ③ 成功后调状态机 PAY_SUCCESS。
         *     本地开发（provider=mock）可直接 POST 该接口模拟回调。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功（返回给微信的应答） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example SUCCESS */
                            code?: string;
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{orderNo}/mock-pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 模拟支付成功（仅本地开发）
         * @description 开发期替代微信支付回调，触发状态机 PAY_SUCCESS 事件（WAIT_PAY → WAIT_KEY）。
         *     由配置项 wash.pay.mock-enabled 控制，生产环境必须为 false，否则返回 A0003。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["PayResultVO"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderNo}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 提交评价
         * @description 走状态机 REVIEW_SUBMIT 事件（WAIT_REVIEW → FINISHED）。≤4 星强制填原因并生成复盘工单。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        rating: number;
                        /** @description 洗得干净 / 时效快 / 服务态度好 / 取送准时 */
                        tags?: string[];
                        content?: string;
                        /** @description 已上传图片的 fileId */
                        images?: string[];
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/after-sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交售后（重洗 / 退款 / 理赔） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        orderNo: string;
                        /** @enum {string} */
                        type: "REWASH" | "REFUND" | "CLAIM";
                        reason?: string;
                        images?: string[];
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: {
                                ticketNo?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上传影像证据
         * @description multipart 上传。大小与类型限制由服务端配置（wash.media），前端不要自行放宽。
         *     bizType 决定这张图属于哪个环节（停车 / 取车 / 洗后 / 还车 / 对比 / 视频）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                        /** @enum {string} */
                        bizType: "PARK" | "PICK" | "WASHED" | "RETURN" | "COMPARE" | "VIDEO";
                        orderNo?: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["MediaVO"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{fileId}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取影像原文件
         * @description 需登录；服务端按 fileId 定位文件，不向前端暴露磁盘路径。
         *     小程序 image / previewImage 组件无法携带 Authorization 头，故支持 query 参数 token
         *     （与 header 二选一）。token 进 URL 有被日志记录的风险，只用于图片读取这个低敏场景，
         *     其余接口一律走 header。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 访问令牌；供 image / previewImage 等无法带 header 的场景使用 */
                    token?: string;
                };
                header?: never;
                path: {
                    fileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 文件流 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/*": string;
                        "video/*": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/faqs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 常见问题标签与解答 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["FaqVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/customer-service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 客服配置（企微二维码、双电话、夜间提示）
         * @description 取值优先级：后台「系统管理 → 参数设置」（key：wash.cs.platform-phone / wash.cs.station-phone /
         *     wash.cs.night-tip / wash.cs.wecom-qrcode-url）→ application.yml 兜底 → 代码默认。
         *     platformPhone 默认 10086：客服入口任何时候都必须能拨通（bug092203）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: {
                                wecomQrcodeUrl?: string;
                                platformPhone?: string;
                                stationPhone?: string;
                                nightTip?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coupons/center": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 领券中心
         * @description 返回当前可领的券模板，含该会员已领数量与剩余库存。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["CouponTemplateVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coupons/templates/{templateId}/receive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 领取优惠券 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    templateId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["CouponUserVO"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coupons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的优惠券 */
        get: {
            parameters: {
                query?: {
                    status?: "UNUSED" | "USED" | "EXPIRED";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["CouponUserVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coupons/best": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 下单页算最优券
         * @description 给定支付金额，返回可用且减免最多的券（可能为空）。
         */
        get: {
            parameters: {
                query: {
                    /** @description 待支付金额（分） */
                    amount: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["CouponBestVO"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insurances/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 可投保产品列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["InsuranceProductVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insurances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的保单 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["InsurancePolicyVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 投保（dev 模式直接生效） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: int64 */
                        productId: number;
                        /** Format: int64 */
                        vehicleId: number;
                        orderNo?: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"] & {
                            data?: components["schemas"]["InsurancePolicyVO"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pick/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 师傅任务池（待取 / 待送）
         * @description 返回当前师傅可见的待取车（KEY_IN / PICKING / TO_STATION）与待送回（WAIT_RETURN / RETURNING）订单列表。
         *     待取车必须从 KEY_IN 起：师傅先从柜中取走钥匙（take-key），才有后续取车动作；
         *     少了 KEY_IN 师傅在任务池里看不到单，取钥匙就没有入口。
         */
        get: {
            parameters: {
                query?: {
                    /** @description PICKUP=待取车；RETURN=待送回；ALL=全部（默认） */
                    stage?: "PICKUP" | "RETURN" | "ALL";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 任务列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: components["schemas"]["PickTaskVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pick/orders/{orderNo}/pick-car-done": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取车拍照完成（触发 PICK_CAR_DONE）
         * @description 触发状态机 PICK_CAR_DONE：PICKING → TO_STATION。
         *     **必填 ≥6 张 360° 照片 + 仪表盘**（bizType=PICK），否则后端拒绝。详见《订单状态机规则表.md》。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 上传后的 fileId 列表，bizType=PICK */
                        fileIds: string[];
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pick/orders/{orderNo}/return-done": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 送回停放完成 + 钥匙归柜（触发 RETURN_DONE）
         * @description 触发状态机 RETURN_DONE：RETURNING → RETURNED。
         *     **必填停放照（含车位号）**（bizType=RETURN），否则后端拒绝。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 停放照 fileId 列表，bizType=RETURN */
                        fileIds: string[];
                        /** @description 车位号 */
                        parkingNo: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/station/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 中央站工位队列看板
         * @description 返回中央站作业台：待入场（TO_STATION）、清洗中（WASHING）、待质检（QC）、待还车（WAIT_RETURN）订单。
         *     WASHING 进 bays，其余进 waiting，前端按 status 分栏渲染并给出对应动作（入场 / SOP / 质检 / 驶离）。
         *     只返回 WASHING / QC 会让 arrive 与 leave 没有入口。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 工位队列 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: components["schemas"]["StationQueueVO"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/station/orders/{orderNo}/sop-done": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * SOP 全部完成（触发 SOP_DONE）
         * @description 触发状态机 SOP_DONE：WASHING → QC；15 步打卡明细后端按 step 记录，这里汇总提交
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 已完成的 15 步 SOP 步骤标识 */
                        steps?: string[];
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/station/orders/{orderNo}/qc-pass": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 质检通过（触发 QC_PASS）
         * @description 触发状态机 QC_PASS：QC → WAIT_RETURN。
         *     **必填洗后照**（bizType=WASHED，前后对比图由后端自动拼），否则后端拒绝。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 洗后照 fileId 列表，bizType=WASHED */
                        fileIds: string[];
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/station/orders/{orderNo}/qc-fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 质检不合格（触发 QC_FAIL）
         * @description 触发状态机 QC_FAIL：QC → WASHING；必填原因，重洗次数 +1，≥2 次自动生成复盘工单
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pick/orders/{orderNo}/take-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取钥匙（触发 TAKE_KEY）
         * @description 触发状态机 TAKE_KEY：KEY_IN → PICKING。师傅从柜中取出客户钥匙、开始取车作业。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/station/orders/{orderNo}/arrive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 入场打卡（触发 ARRIVE_STATION）
         * @description 触发状态机 ARRIVE_STATION：TO_STATION → WASHING；记录到站点时间。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/station/orders/{orderNo}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 驶离站点（触发 LEAVE_STATION）
         * @description 触发状态机 LEAVE_STATION：WAIT_RETURN → RETURNING；记录离站时间。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderNo: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CouponTemplateVO: {
            /** Format: int64 */
            templateId?: number;
            name?: string;
            /** @enum {string} */
            type?: "NORMAL" | "NEWBIE";
            /**
             * Format: int64
             * @description 使用门槛（分）
             */
            thresholdAmount?: number;
            /**
             * Format: int64
             * @description 减免金额（分）
             */
            discountAmount?: number;
            perLimit?: number;
            /**
             * Format: int64
             * @description 失效时间（毫秒）
             */
            endTime?: number;
            /** @description 剩余库存 */
            remain?: number;
            /** @description 当前会员已领数量 */
            claimed?: number;
        };
        CouponUserVO: {
            /** Format: int64 */
            couponUserId?: number;
            /** Format: int64 */
            templateId?: number;
            name?: string;
            /** Format: int64 */
            thresholdAmount?: number;
            /** Format: int64 */
            discountAmount?: number;
            /** @enum {string} */
            status?: "UNUSED" | "USED" | "EXPIRED";
            /** Format: int64 */
            expireTime?: number;
            orderNo?: string;
        };
        CouponBestVO: {
            /** Format: int64 */
            couponUserId?: number;
            /** Format: int64 */
            discountAmount?: number;
        };
        InsuranceProductVO: {
            /** Format: int64 */
            productId?: number;
            name?: string;
            /**
             * Format: int64
             * @description 保费（分）
             */
            priceAmount?: number;
            coverageDesc?: string;
        };
        InsurancePolicyVO: {
            /** Format: int64 */
            policyId?: number;
            policyNo?: string;
            /** Format: int64 */
            productId?: number;
            name?: string;
            /** Format: int64 */
            vehicleId?: number;
            orderNo?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "EXPIRED" | "CANCELED";
            /** Format: int64 */
            startTime?: number;
            /** Format: int64 */
            endTime?: number;
            /**
             * Format: int64
             * @description 实付保费（分）
             */
            paidAmount?: number;
        };
        Result: {
            /**
             * @description 0 = 成功，非 0 见 x-error-codes。
             *     数字映射规则：分段字母转前缀（A=1 / B=2 / C=3）+ 4 位编号，
             *     即 A0002 → 10002、B1002 → 21002、C0001 → 30001。
             * @example 0
             */
            code: number;
            /** @example 操作成功 */
            msg: string;
            /** @description 业务数据，各接口不同 */
            data?: unknown;
            /** @description 链路追踪 ID，排查问题时提供 */
            traceId?: string;
        };
        /**
         * @description 订单状态，取值必须与《订单状态机规则表.md》及 OrderStatus 枚举完全一致（15 个）。
         * @enum {string}
         */
        OrderStatus: "WAIT_PAY" | "WAIT_KEY" | "KEY_IN" | "PICKING" | "TO_STATION" | "WASHING" | "QC" | "WAIT_RETURN" | "RETURNING" | "RETURNED" | "WAIT_REVIEW" | "FINISHED" | "CANCELED" | "REFUNDING" | "REFUNDED";
        TimelineNode: {
            /**
             * @description 已下单 / 钥匙已入柜 / 已取车 / 到达中央站 / 清洗中 / 质检完成 / 已还车 / 待取钥匙
             * @enum {string}
             */
            node?: "ORDERED" | "KEY_IN" | "PICKED" | "ARRIVED" | "WASHING" | "QC_DONE" | "RETURNED" | "WAIT_TAKE_KEY";
            title?: string;
            /**
             * Format: int64
             * @description 毫秒时间戳，未到达时为空
             */
            time?: number;
            reached?: boolean;
            current?: boolean;
            /** @description 该节点的照片等证据 */
            evidences?: components["schemas"]["MediaVO"][];
        };
        WorkerLoginVO: {
            token?: string;
            /** Format: int64 */
            expireAt?: number;
            /** Format: int64 */
            workerId?: number;
            /** @description 工号 */
            workerNo?: string;
            name?: string;
            /** Format: int64 */
            siteId?: number;
            siteName?: string;
            /**
             * @description 正常 / 禁用
             * @enum {string}
             */
            status?: "NORMAL" | "DISABLED";
        };
        LoginVO: {
            token?: string;
            /** Format: int64 */
            expireAt?: number;
            isNewUser?: boolean;
            /** @description true 时前端弹《用户服务协议》《隐私政策》 */
            needAgreement?: boolean;
            phoneBound?: boolean;
        };
        SiteVO: {
            /** Format: int64 */
            siteId?: number;
            siteName?: string;
            /** Format: int64 */
            communityId?: number;
            communityName?: string;
            /** @description 站点栏展示文案，如「泷景花园 · 泷景中央站」 */
            displayName?: string;
            /**
             * @description 正常 / 停业 / 雨天模式
             * @enum {string}
             */
            serviceStatus?: "OPEN" | "CLOSED" | "RAINY";
            closedNotice?: string;
        };
        CommunityVO: {
            /** Format: int64 */
            communityId?: number;
            name?: string;
            /** @description 地库通行授权，false 时禁止该小区下单 */
            accessAuth?: boolean;
            enabled?: boolean;
        };
        BannerVO: {
            /** Format: int64 */
            bannerId?: number;
            imageUrl?: string;
            title?: string;
            /** @enum {string} */
            linkType?: "NONE" | "ACTIVITY" | "RECHARGE" | "SERVICE";
            linkValue?: string;
            sort?: number;
        };
        CapacityVO: {
            /** Format: date */
            date?: string;
            total?: number;
            used?: number;
            remaining?: number;
            /** @description 最晚存钥匙时间，如 23:00 */
            depositDeadline?: string;
            /** @description 承诺还车时间，如 次日 07:00 */
            promiseReturnTime?: string;
            soldOut?: boolean;
        };
        ServiceCategoryVO: {
            /** Format: int64 */
            categoryId?: number;
            /** @example 洗车服务 */
            name?: string;
            sort?: number;
        };
        ServiceVO: {
            /** Format: int64 */
            serviceId?: number;
            /** Format: int64 */
            categoryId?: number;
            name?: string;
            subtitle?: string;
            /** @description 原价，单位分 */
            originPrice?: number;
            /** @description 活动价，单位分 */
            salePrice?: number;
            /** @description 会员价，单位分；非会员为空 */
            memberPrice?: number;
            /** @description 实际展示价，优先级 会员价 > 活动价 > 原价，由后端算好 */
            displayPrice?: number;
            workMinutes?: number;
            /** @description 取送车费，固定展示 0（卖点） */
            pickupFee?: number;
            dailyLimit?: number;
            /** @description 今日已约满 */
            soldOut?: boolean;
            coverUrl?: string;
        };
        ServiceDetailVO: components["schemas"]["ServiceVO"] & {
            /** @description 服务内容清单 */
            items?: string[];
            applicableModels?: string;
            notIncluded?: string[];
            notices?: string[];
            sampleImages?: string[];
        };
        CabinetVO: {
            /** Format: int64 */
            cabinetId?: number;
            /** @description 命名规范 小区名+楼栋+单元+楼层，如「泷景花园 三号楼二单元负一」 */
            name?: string;
            slotTotal?: number;
            slotFree?: number;
            online?: boolean;
            /** @description 距您约多少米；未授权定位时为空 */
            distance?: number;
            full?: boolean;
        };
        VehicleVO: {
            /** Format: int64 */
            vehicleId?: number;
            plateNo?: string;
            brand?: string;
            color?: string;
            photoUrl?: string;
            isNewEnergy?: boolean;
            isDefault?: boolean;
            address?: components["schemas"]["AddressVO"];
        };
        AddressVO: {
            /** Format: int64 */
            communityId?: number;
            building?: string;
            unit?: string;
            /** @example 负一层 */
            floor?: string;
            /** @example A 区 23 号车位 */
            parkingNo?: string;
        };
        VehicleRequest: {
            /** @description 支持新能源 8 位 */
            plateNo: string;
            brand?: string;
            color?: string;
            photoFileId?: string;
            isNewEnergy?: boolean;
            isDefault?: boolean;
            address?: components["schemas"]["AddressVO"];
        };
        CreateOrderRequest: {
            /** Format: int64 */
            serviceId: number;
            /** Format: int64 */
            vehicleId: number;
            /** Format: int64 */
            cabinetId: number;
            /** Format: date */
            appointDate: string;
            /** @example 19:00 */
            appointTime: string;
            /**
             * @description 是否需要取送车，V1.0 固定 true
             * @default true
             */
            pickupRequired: boolean;
            remark?: string;
            /** @description 停放照片，最多 6 张（bug092204）；先经 media/upload 上传后引用 fileId */
            parkPhotoFileIds?: string[];
            /** @description 已同意《服务条款与钥匙寄存协议》 */
            agreed: boolean;
            /**
             * Format: int64
             * @description 使用的优惠券 ID（来自「我的优惠券」UNUSED 券），不传则不使用优惠券
             */
            couponUserId?: number;
        };
        CreateOrderVO: {
            /** @example SE202609151601276839838676768265 */
            orderNo?: string;
            status?: components["schemas"]["OrderStatus"];
            /** @description 应付金额，单位分（已扣除优惠券抵扣） */
            payAmount?: number;
            /**
             * Format: int64
             * @description 优惠券抵扣金额，单位分；未用券时为 0
             */
            couponDiscount?: number;
            /**
             * Format: int64
             * @description 支付截止时间，毫秒时间戳
             */
            payExpireAt?: number;
        };
        OrderListItemVO: {
            orderNo?: string;
            status?: components["schemas"]["OrderStatus"];
            statusLabel?: string;
            serviceName?: string;
            workMinutes?: number;
            /** Format: int64 */
            appointTime?: number;
            communityName?: string;
            plateNo?: string;
            payAmount?: number;
            mainAction?: components["schemas"]["OrderAction"];
            subActions?: components["schemas"]["OrderAction"][];
        };
        OrderDetailVO: {
            orderNo?: string;
            status?: components["schemas"]["OrderStatus"];
            statusLabel?: string;
            /** @example 清洗中 · 预计次日 6:30 送回原位 */
            statusDesc?: string;
            /** Format: int64 */
            promiseReturnTime?: number;
            overdue?: boolean;
            siteName?: string;
            cabinetName?: string;
            /** @description 仅本人可见 */
            slotNo?: string;
            plateNo?: string;
            address?: components["schemas"]["AddressVO"];
            serviceName?: string;
            remark?: string;
            originAmount?: number;
            discountAmount?: number;
            payAmount?: number;
            payType?: string;
            timeline?: components["schemas"]["TimelineNode"][];
            medias?: components["schemas"]["MediaVO"][];
            mainAction?: components["schemas"]["OrderAction"];
            subActions?: components["schemas"]["OrderAction"][];
        };
        /** @description 模拟支付返回（x-dev-only） */
        PayResultVO: {
            orderNo?: string;
            status?: components["schemas"]["OrderStatus"];
        };
        /** @description 按钮随状态机变化，前端不得自行推断，一律用后端返回值 */
        OrderAction: {
            /** @enum {string} */
            action?: "PAY" | "DEPOSIT_KEY" | "VIEW_PROGRESS" | "TAKE_KEY" | "REVIEW" | "REORDER" | "CANCEL" | "CONTACT_SERVICE";
            label?: string;
            enabled?: boolean;
        };
        OpenCodeVO: {
            /** @description 6 位取件码 */
            code?: string;
            qrcodeUrl?: string;
            cabinetName?: string;
            slotNo?: string;
            /** Format: int64 */
            expireAt?: number;
        };
        MediaVO: {
            fileId?: string;
            /** @enum {string} */
            bizType?: "PARK" | "PICK" | "WASHED" | "RETURN" | "COMPARE" | "VIDEO";
            /** @description 临时访问地址，带有效期 */
            url?: string;
            /** Format: int64 */
            uploadTime?: number;
        };
        /** @description 任务池单项（取送端） */
        PickTaskVO: {
            orderNo?: string;
            /**
             * @description 待取车 / 待送回
             * @enum {string}
             */
            bizType?: "PICKUP" | "RETURN";
            status?: components["schemas"]["OrderStatus"];
            /** @description 状态中文名，由后端 OrderStatus 枚举给出；前端禁止自行翻译状态码 */
            statusLabel?: string;
            /** @description 用户上传的停车照（bizType=PARK），师傅找车用；无照片时为空数组 */
            parkPhotos?: components["schemas"]["MediaVO"][];
            serviceName?: string;
            /** @description 车牌 */
            vehiclePlate?: string;
            vehicleBrand?: string;
            vehicleColor?: string;
            /** @description 客户称呼，脱敏 */
            customerName?: string;
            /** @description 联系电话，脱敏 */
            customerPhone?: string;
            pickupAddr?: string;
            returnAddr?: string;
            /**
             * Format: date
             * @description 预约服务日
             */
            appointmentDate?: string;
            /** @description 承诺还车时间，如 次日 07:00 */
            promiseReturnTime?: string;
            /** @description 最晚存钥匙时间 */
            pickupDeadline?: string;
            /** @description 取车需拍照片数（≥6） */
            requiredPhotoCount?: number;
            /** @description 距师傅当前位置约多少米；未定位时为空 */
            distanceMeters?: number;
        };
        /** @description 中央站工位队列看板项 */
        StationQueueVO: {
            /** Format: int64 */
            stationId?: number;
            stationName?: string;
            /** @description 清洗中数量 */
            washingCount?: number;
            /** @description 待质检数量 */
            qcCount?: number;
            /** @description 工位列表 */
            bays?: {
                /** @description 工位号 */
                bayNo?: string;
                orderNo?: string;
                status?: components["schemas"]["OrderStatus"];
                /**
                 * Format: int64
                 * @description 进入该工位时间（毫秒）
                 */
                startedAt?: number;
                /** @description 当前 15 步 SOP 进度，WASHING 时有效 */
                sopStep?: number;
            }[];
            /**
             * @description 非「在洗」的订单，含待入场（TO_STATION）/ 待质检（QC）/ 待还车（WAIT_RETURN）。
             *     status 必带：前端据此决定给出「入场 / 质检 / 驶离」哪个动作。
             */
            waiting?: {
                orderNo?: string;
                serviceName?: string;
                status?: components["schemas"]["OrderStatus"];
                /** Format: int64 */
                queuedAt?: number;
            }[];
        };
        FaqVO: {
            /** Format: int64 */
            faqId?: number;
            /** @example 无法打开柜门 */
            label?: string;
            answer?: string;
            /** @description 绑定的工单类型，一键建单时带入 */
            ticketType?: string;
        };
    };
    responses: never;
    parameters: {
        PageNum: number;
        PageSize: number;
        SiteId: number;
        CommunityId: number;
        /** @description 幂等键，客户端生成 UUID，同一键重复提交返回首次结果 */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
